import Head from 'next/head'
import Hero from '../components/Hero';
import heroBackgroundImageHome from '../public/images/convictlake.jpg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        image={heroBackgroundImageHome}
        heading='Eugene Kim'
        message='Software Engineer'
        action='About me'
        link='#aboutMe'
        position='object-left'
      />
      <div id='aboutMe' className='relative flex h-screen items-center justify-center'>
        <h1 className='absolute top-40 text-4xl font-bold text-center mb-12'>About Me</h1>
        <div className='flex max-w-4xl justify-between'>
          
        </div>
      </div>
    </>
  )
}
